### ISSUE TITLE
Deploying Azure COSMOS DB Binding crashes the POD

### ISSUE THREAD

**Issue by ubhanja** [dapr/components-contrib#1088] opened 2021-08-17 15:12 UTC
I have a producer deployment (yaml is attached) which is posting data to Azure service bus queue binding in DAPR. This producer works fine with Azure Service BUS binding. I created a new Cosmos DB Binding (attached is the binding Yaml). As soon as the binding is deployed in default namespace the producer pod crashes. I increased the request and limit memory but still the issue continues. If I delete the binding component for Azure Cosmos DB , POD starts running. I am able to shell into the POD and post data at 3500 port for Azure Service bus . I created a state store for COSMOS DB and it works. I am able to save the data in COSMOS DB using statestore. But for bindings it is failing. I have the POD logs and DAPR container logs attached with yaml file. Appreciate if you can provide some input on why bindings in cosmos DB is causing the POD to crash,
[daprdeploy.zip](https://github.com/dapr/components-contrib/files/7001109/daprdeploy.zip)

**Comment by CodeMonkeyLeet** [comment] 2021-08-18 22:24
Dupe of #1092?

**Comment by ubhanja** [comment] 2021-08-19 02:33
Sorry . It is dupe . I will remove .

**Comment by ubhanja** [comment] 2021-08-19 05:14
Duplicate of 1092. Closing this.

**Closed** 2021-08-19 05:13 UTC
