### ISSUE TITLE
Redis state store: using "first-write" and no etag updates the document if it exists

### ISSUE THREAD

**Issue by ItalyPaleAle** [dapr/components-contrib#1010] opened 2021-07-14 04:21 UTC
As requested, this is a bug report following up my experience from https://github.com/dapr/dapr/issues/2739#issuecomment-864721906

## Expected Behavior

When using "first-write" as concurrency mode and no etag, the operation should fail if a value for the same key already exists.

## Actual Behavior

With Redis as state store, setting no etag makes Dapr overwrite the value even if concurrency is "first-write".

(As a workaround, I've been setting the etag to "2147483647", or 0x7FFFFFFF, the largest int32 value)

## Steps to Reproduce the Problem

First, in an empty folder create the file `components/state.yaml`:

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: documents
spec:
  type: state.redis
  version: v1
  metadata:
    - name: redisHost
      value: "localhost:6379"
    - name: redisPassword
      value: ""
    - name: keyPrefix
      value: name
```

Then create this script to test the behavior:

```sh
#!/bin/bash

dapr run \
  --app-id testapp \
  --dapr-http-port 5500 \
  --components-path ./components \
  sleep 120 \
  > dapr-log \
  &
PID=$!
echo -e "PID: $PID"

sleep 5

echo -e "\n\nFirst request with etag = 2147483647 - should not show an error"
curl -X POST -H "Content-type: application/json" -d '[
  {
    "key": "1234abcd",
    "value": "Hello world 1",
    "etag": "2147483647",
    "options": {
      "concurrency": "first-write",
      "consistency": "strong"
    }
  }
]' 'http://localhost:5500/v1.0/state/documents'
echo -e "\nValue should be 'Hello world 1'"
curl 'http://localhost:5500/v1.0/state/documents/1234abcd'

echo -e "\n\nSecond request with etag = 2147483647 - should fail"
curl -X POST -H "Content-type: application/json" -d '[
  {
    "key": "1234abcd",
    "value": "Hello world 2",
    "etag": "2147483647",
    "options": {
      "concurrency": "first-write",
      "consistency": "strong"
    }
  }
]' 'http://localhost:5500/v1.0/state/documents'
echo -e "\nValue should be 'Hello world 1'"
curl 'http://localhost:5500/v1.0/state/documents/1234abcd'

echo -e "\n\nFirst request with no etag - should not show an error"
curl -X POST -H "Content-type: application/json" -d '[
  {
    "key": "AaAaBbBb",
    "value": "Hello world 1",
    "options": {
      "concurrency": "first-write",
      "consistency": "strong"
    }
  }
]' 'http://localhost:5500/v1.0/state/documents'
echo -e "\nValue should be 'Hello world 1'"
curl 'http://localhost:5500/v1.0/state/documents/AaAaBbBb'

echo -e "\n\nSecond request with no etag - should fail"
curl -X POST -H "Content-type: application/json" -d '[
  {
    "key": "AaAaBbBb",
    "value": "Hello world 2",
    "options": {
      "concurrency": "first-write",
      "consistency": "strong"
    }
  }
]' 'http://localhost:5500/v1.0/state/documents'
echo -e "\nValue should be 'Hello world 1'"
curl 'http://localhost:5500/v1.0/state/documents/AaAaBbBb'

kill $PID
```

Run the script. The result will be:

```text
$ ./test.sh
PID: 6114


First request with etag = 2147483647 - should not show an error

Value should be 'Hello world 1'
"Hello world 1"

Second request with etag = 2147483647 - should fail
{"errorCode":"ERR_STATE_SAVE","message":"failed saving state in state store documents: possible etag mismatch. error from state store: ERR Error running script (call to f_83e03ec05d6a3b6fb48483accf5e594597b6058f): @user_script:1: user_script:1: failed to set key documents||1234abcd"}
Value should be 'Hello world 1'
"Hello world 1"

First request with no etag - should not show an error

Value should be 'Hello world 1'
"Hello world 1"

Second request with no etag - should fail

Value should be 'Hello world 1'
"Hello world 2"
```

At the very end, where it says "Second request with no etag - should fail", you see that the request succeeds (there's no error) and that the value retrieved is "Hello world 1". We expected to get an error (similar to the one above) and expected the value to be "Hello world 1"

## Release Note

RELEASE NOTE:

**Comment by daixiang0** [comment] 2021-07-14 05:28
something like #994 ?

**Comment by ItalyPaleAle** [comment] 2021-07-14 06:11
Yes it looks the same.

Code here should allow replicating the issue.

**Comment by artursouza** [comment] 2021-07-22 23:23
Please, add conformance test to validate/fix the same in other state stores.

**Comment by ItalyPaleAle** [comment] 2021-07-23 05:34
@artursouza are you asking me?
(ps I'll be on vacation till early august)

**Comment by artursouza** [comment] 2021-07-23 22:43
@ItalyPaleAle No, I am just adding a comment to increase the scope of the issue for whoever works on this.

**Comment by artursouza** [comment] 2021-07-23 22:45
Closing as duplicate of #994

**Closed by artursouza** 2021-07-23 22:45 UTC
Labels: P1, area/runtime/state, kind/bug, size/M, triaged/resolved
