### ISSUE TITLE
Azure Service Bus Queues - Messages aren't processed

### ISSUE THREAD

**Issue by fabistb** [dapr/components-contrib#874] opened 2021-05-17 16:14 UTC
## Expected Behavior
When a new message is added to the queue it is getting picked and processed.

## Actual Behavior
Messages are added to the queue but are not getting processed.
The message stays on the queue until the service is restarted.

## Steps to Reproduce the Problem
Not sure how to reproduce this problem.
It looks like the time might be a factor. 

## Logs
The sidecar logs show only logs related to topics.
However when these logs show the message isn't picked.

`time="2021-05-12T11:17:26.880197929Z" level=error msg="azure service bus error: closing subscription entity for topic mytopic: link detached, reason: *Error{Condition: amqp:link:detach-forced, Description: The link 'Vzm4yJeTDttf8FfVjnIb34nhexzvMBUwUUJrwLQ3Br82A82oU4RdBQ' is force detached. Code: RenewToken. Details: Unauthorized access. 'Listen' claim(s) are required to perform this operation. Resource: 'sb://my-sb.servicebus.windows.net/mytopic/subscriptions/myapp'.. TrackingId:091bc1dfac4341e6bcd27d2a6812f4a2_G17, SystemTracker:gateway5, Timestamp:2021-05-12T11:17:26, Info: map[]}" app_id=myapp instance=myapp-bf7cfd676-4z4mf scope=dapr.contrib type=log ver=1.1.2
time="2021-05-12T11:17:26.88027673Z" level=error msg="azure service bus error: error receiving message on topic mytopic, link detached, reason: *Error{Condition: amqp:link:detach-forced, Description: The link 'Vzm4yJeTDttf8FfVjnIb34nhexzvMBUwUUJrwLQ3Br82A82oU4RdBQ' is force detached. Code: RenewToken. Details: Unauthorized access. 'Listen' claim(s) are required to perform this operation. Resource: 'sb://my-sb.servicebus.windows.net/mytopic/subscriptions/myapp'.. TrackingId:091bc1dfac4341e6bcd27d2a6812f4a2_G17, SystemTracker:gateway5, Timestamp:2021-05-12T11:17:26, Info: map[]}" app_id=myapp instance=myapp-bf7cfd676-4z4mf scope=dapr.contrib type=log ver=1.1.2
time="2021-05-12T11:17:26.88030943Z" level=warning msg="Subscription to topic mytopic lost connection, attempting to reconnect... [0/30]" app_id=<my_app> instance=myapp-bf7cfd676-4z4mf scope=dapr.contrib type=log ver=1.1.2
time="2021-05-12T11:27:28.804022788Z" level=error msg="azure service bus error: closing subscription entity for topic mytopic: link detached, reason: *Error{Condition: amqp:link:detach-forced, Description: The link '_hNBVPdnTd2T6msByXjNO60_cSghh_HrQE-kggy7Pme1oW_4ecIV0g' is force detached. Code: RenewToken. Details: Unauthorized access. 'Listen' claim(s) are required to perform this operation. Resource: 'sb://my-sb.servicebus.windows.net/mytopic/subscriptions/myapp'.. TrackingId:091bc1dfac4341e6bcd27d2a6812f4a2_G17, SystemTracker:gateway5, Timestamp:2021-05-12T11:27:28, Info: map[]}" app_id=myapp instance=myapp-bf7cfd676-4z4mf scope=dapr.contrib type=log ver=1.1.2
time="2021-05-12T11:27:28.804099089Z" level=error msg="azure service bus error: error receiving message on topic mytopic, link detached, reason: *Error{Condition: amqp:link:detach-forced, Description: The link '_hNBVPdnTd2T6msByXjNO60_cSghh_HrQE-kggy7Pme1oW_4ecIV0g' is force detached. Code: RenewToken. Details: Unauthorized access. 'Listen' claim(s) are required to perform this operation. Resource: 'sb://my-sb.servicebus.windows.net/mytopic/subscriptions/myapp'.. TrackingId:091bc1dfac4341e6bcd27d2a6812f4a2_G17, SystemTracker:gateway5, Timestamp:2021-05-12T11:27:28, Info: map[]}" app_id=myapp instance=myapp-bf7cfd676-4z4mf scope=dapr.contrib type=log ver=1.1.2
time="2021-05-12T11:27:28.80433519Z" level=warning msg="Subscription to topic mytopic lost connection, attempting to reconnect... [0/30]" app_id=myapp instance=myapp-bf7cfd676-4z4mf scope=dapr.contrib type=log ver=1.1.2
time="2021-05-12T11:27:28.85934655Z" level=error msg="azure service bus error: closing subscription entity for topic mytopic: link detached, reason: *Error{Condition: amqp:link:detach-forced, Description: The link 'abGS1YE5Wo7cSCl6Zw5tLw45zLg_N7dsCQ_zFbg3K5V8ppSuSoueEw' is force detached. Code: RenewToken. Details: Unauthorized access. 'Listen' claim(s) are required to perform this operation. Resource: 'sb://my-sb.servicebus.windows.net/mytopic/subscriptions/myapp'.. TrackingId:afedcf6dc6e64d0a8aa3754560210c05_G3, SystemTracker:gateway5, Timestamp:2021-05-12T11:27:28, Info: map[]}" app_id=myapp instance=myapp-bf7cfd676-4z4mf scope=dapr.contrib type=log ver=1.1.2
time="2021-05-12T11:27:28.85941445Z" level=error msg="azure service bus error: error receiving message on topic mytopic, link detached, reason: *Error{Condition: amqp:link:detach-forced, Description: The link 'abGS1YE5Wo7cSCl6Zw5tLw45zLg_N7dsCQ_zFbg3K5V8ppSuSoueEw' is force detached. Code: RenewToken. Details: Unauthorized access. 'Listen' claim(s) are required to perform this operation. Resource: 'sb://my-sb.servicebus.windows.net/mytopic/subscriptions/myapp'.. TrackingId:afedcf6dc6e64d0a8aa3754560210c05_G3, SystemTracker:gateway5, Timestamp:2021-05-12T11:27:28, Info: map[]}" app_id=myapp instance=myapp-bf7cfd676-4z4mf scope=dapr.contrib type=log ver=1.1.2
time="2021-05-12T11:27:28.859632652Z" level=warning msg="Subscription to topic mytopic lost connection, attempting to reconnect... [0/30]" app_id=myapp instance=myapp-bf7cfd676-4z4mf scope=dapr.contrib type=log ver=1.1.2`

## Release Note
**Fix** Azure Service Bus Queues Messages not picked

**Comment by jjcollinge** [comment] 2021-05-17 20:29
Hi, thanks for the issue. Could you help me understand the problem a little more please? The logs indicate that the connection string you are using does not have the require permissions. Is this not the root cause?

**Comment by yaron2** [comment] 2021-05-17 20:55
Hey @fabistb which Dapr version are you using?

**Comment by fabistb** [comment] 2021-05-18 11:51
> Hi, thanks for the issue. Could you help me understand the problem a little more please? You mention 'queues'. Are you using the Azure Service Bus PubSub component or the Azure Service Bus Queue Binding? The PubSub component currently only works with topics. The logs look like the PubSub errors and indicate that the connection string you are using does not have the required permissions (the Listen claim) on the topic. This might indicate you are supplying a connection string for a queue rather than a topic. Is this the case?

Hi, I'm referring to the Azure Service Bus Queue Binding. 
Unfortunately I wasn't able to find any Queue Binding related logs in the dapr sidecar. However these topic related logs are currently the best indication I found to check if messages will be picked or not. After restarting the service everything works as expected. 

I checked the ServiceBus connection string. Based on the Azure Portal the connection string should have the required permissions. 
As a side note. Currently the same connection string for the PubSub component and Azure Queue Binding is used.

>Hey @fabistb which Dapr version are you using?

Hi, the cluster uses dapr version 1.1.2.

**Comment by fabistb** [comment] 2021-06-18 12:55
Hey @jjcollinge , @yaron2 ,

unfortunately this problem also occurs using version 1.2.0.
It also looks like that this problem is service specific even though all components are using the same connection string on service bus level.

Service A successfully processes the queue messages while Service B shows these topic errors and doesn't process the messages.

Any suggestion how I can debug this in detail to provide better logs?
Currently I mainly check the daprd logs for the affected service. 

`kubectl logs <podName> -n <namespace> daprd`

**Comment by fabistb** [comment] 2021-08-02 06:45
Hi @yaron2 , @artursouza ,
it would be great if we could keep this issue open.

Thanks!

**Comment by artursouza** [comment] 2021-08-04 00:41
@fabistb We had made improvements to Azure Service Bus in PubSub related to this. Is there a reason why you need binding and cannot use PubSub?

**Comment by fabistb** [comment] 2021-08-05 20:03
@artursouza I wan't to ensure that only one consumer processes the messages.
Also one downside of Azure Service Bus Topics is that when dead lettered messages moved back to the active they are processed by all subscribers again independent if a subscriber was previously able process the message.
We often have the case that we must ensure that a message is only processed once. In cases of multiple subscribers we push the message to a topic using PubSub and then forward it to multiple queues where our services pick the message from.

**Comment by bgelens** [comment] 2021-09-15 07:30
We are experiencing the same on dapr 1.2 using just pubsub. Multiple clusters at the same time. Only thing we can do is restart rollout.

`2021-09-15T05:52:09.809Z  time="2021-09-15T05:52:09.809304727Z" level=error msg="azure service bus error: error receiving message on topic REDACTED, link detached, reason: *Error{Condition: amqp:link:detach-forced, Description: The link 'SfpRLmiAbJgr9e1tqh8pHkZ7xDDkRJaTc4bplkN9nlk2DPnoV_iHbQ' is force detached. Code: RenewToken. Details: Unauthorized access. 'Listen' claim(s) are required to perform this operation. Resource: 'REDACTED'.. TrackingId:62d462fb5fd548e29418a58cdebbb11d_G24, SystemTracker:gateway7, Timestamp:2021-09-15T05:52:09, Info: map[]}" app_id= REDACTED instance= REDACTED scope=dapr.contrib type=log ver=1.2.2
2021-09-15T05:52:09.809Z  time="2021-09-15T05:52:09.809333928Z" level=warning msg="Subscription to topic REDACTED lost connection, attempting to reconnect... [0/30]" app_id= REDACTED instance= REDACTED scope=dapr.contrib type=log ver=1.2.2
2021-09-15T06:57:03.912Z  time="2021-09-15T06:57:03.911865689Z" level=warning msg="azure service bus error: closing subscription entity for topic REDACTED: link detached, reason: *Error{Condition: amqp:link:detach-forced, Description: The link 'QLcCY6xfo57kXvlhZB0XJv4nz7jPLoNyJKy2PP6KO7N4gGlLdM9aEg' is force detached. Code: RenewToken. Details: Unauthorized access. 'Listen' claim(s) are required to perform this operation. Resource: 'REDACTED'.. TrackingId:120749e74bd6464a8f7efb733b0758c6_G2, SystemTracker:gateway7, Timestamp:2021-09-15T06:57:03, Info: map[]}" app_id= REDACTED instance=REDACTED scope=dapr.contrib type=log ver=1.2.2`

**Comment by jjcollinge** [comment] 2021-09-15 08:03
@bgelens thanks for reporting this - is it possible you could raise a separate issue specific to pubsub please and link it back here? Could you please provide as much detail as you can about when you see this error occur in that issue too so I can try to repro?

**Closed** 2021-11-17 17:58 UTC
Labels: kind/bug, area/runtime/binding, P1, size/S, triaged/resolved
