### ISSUE TITLE
Memory Leak in Dapr Container with Confluent Kafka Pub/Sub

### ISSUE THREAD

**Issue by kishanTakeda** [dapr/components-contrib#3064] opened 2023-08-10 11:09 UTC
**Issue Description:**
The Dapr container within my application's pod is experiencing a memory leak issue, causing a continuous increase in memory consumption. This issue is observed when using Confluent Kafka as the service bus and publishing messages using the provided .NET code.

**Steps to Reproduce:**

1. Deploy a pod containing two containers: AppContainer and Dapr container.
2. Utilize the Dapr sidecar pattern to manage interactions.
3. Utilize Confluent Kafka as the service bus for Dapr.
4. Publish messages using the following .NET code:

`await _dapr.PublishEventAsync(DAPR_PUBSUB_NAME, topicName, @event);
`
**Expected Behavior:**
The memory consumption of the Dapr container should remain stable over time, regardless of the number of messages published using the provided .NET core microservice code.

**Actual Behavior:**
The memory consumption of the Dapr container keeps increasing over time as more messages are published using the .NET code. This behavior indicates a memory leak issue within the Dapr container when using Confluent Kafka as the service bus.

![image](https://github.com/dapr/components-contrib/assets/80945137/7dd60ee3-fbfe-4eaa-9b26-309f7db1ca48)

Environment:

Dapr Version: v 1.10
.Net core Image : mcr.microsoft.com/dotnet/aspnet:6.0
Cloud Platform: Openshift 
Service Bus: Confluent Kafka
Programming Language: .NET Core 6.0

**Comment by berndverst** [comment] 2023-08-24 23:32
Closing as duplicate of https://github.com/dapr/dapr/issues/6797

**Closed by berndverst** 2023-08-24 23:32 UTC
