### ISSUE TITLE
[Proposal]: Semantic versioning for configuration items in Configuration Building Block API

### ISSUE THREAD

**Issue by akhilac1** [dapr/components-contrib#2187] opened 2022-10-13 08:52 UTC
## Describe the proposal
Configuration building block GET API allows a user to get 'all' the configuration data when no specific key is specified.
Owing to the current structure of response, only one value can be returned for a key.

https://github.com/dapr/components-contrib/blob/3427cc1c590f1e05cbf202a94f409d042b68bc00/configuration/responses.go#L17-L19

So, when there are multiple versions of a key and no filtering criteria is provided, the configuration building block should to return the latest version. 

To enable reliable comparison of the versions  for configuration items, following are required -
- Specification should be updated to clearly mandate adherence to semantic versioning standards 
- Configuration components should be enhanced to compare and return the configuration item with the latest version, when no filter is specified 
- To support backward compatibility, if version items does not follow standards of semantic versioning, system should compare major and minor versions and return the item with highest version.

**Comment by rabollin** [comment] 2022-10-15 18:20
> ## Describe the proposal
> Configuration building block GET API allows a user to get 'all' the configuration data when no specific key is specified. Owing to the current structure of response, only one value can be returned for a key.
> 
> https://github.com/dapr/components-contrib/blob/3427cc1c590f1e05cbf202a94f409d042b68bc00/configuration/responses.go#L17-L19
> 
> So, when there are multiple versions of a key and no filtering criteria is provided, the configuration building block should to return the latest version.
> 
> To enable reliable comparison of the versions for configuration items, following are required -
> 
> * Specification should be updated to clearly mandate adherence to semantic versioning standards
> * Configuration components should be enhanced to compare and return the configuration item with the latest version, when no filter is specified
> * To support backward compatibility, if version items does not follow standards of semantic versioning, system should compare major and minor versions and return the item with highest version.

Versioning would help with differentiating the configuration changes and App may have more control now, however
1. Does the App need to keep track of the versioning?
2. How do you handle the existing implementations?

**Comment by berndverst** [comment] 2022-10-18 16:15
Does this require an API change or is this just in the implementation in each component?

If this is required of every component, consider enforcing this in the API somehow (and hence the proposal must be in dapr/dapr).

Changes to the API or building block behaviors in general should be discussed via proposal in the `dapr/dapr` repo. You can ask a STC member to transfer this issue there.

**Comment by akhilac1** [comment] 2022-10-19 03:22
> Does this require an API change or is this just in the implementation in each component?
> 
> If this is required of every component, consider enforcing this in the API somehow (and hence the proposal must be in dapr/dapr).
> 
> Changes to the API or building block behaviors in general should be discussed via proposal in the `dapr/dapr` repo. You can ask a STC member to transfer this issue there.

This is a proposal for implementation within the component and how it handles the implementation for GET all API, for all supported components of 'Configuration' building block. There is no change to API for Configuration building block. There is also a need to update spec for configuration building block. 

Added a draft issue in Dapr/docs - https://github.com/dapr/docs/issues/2909

**Comment by akhilac1** [comment] 2022-10-19 03:25
> > ## Describe the proposal
> > Configuration building block GET API allows a user to get 'all' the configuration data when no specific key is specified. Owing to the current structure of response, only one value can be returned for a key.
> > https://github.com/dapr/components-contrib/blob/3427cc1c590f1e05cbf202a94f409d042b68bc00/configuration/responses.go#L17-L19
> > 
> > So, when there are multiple versions of a key and no filtering criteria is provided, the configuration building block should to return the latest version.
> > To enable reliable comparison of the versions for configuration items, following are required -
> > 
> > * Specification should be updated to clearly mandate adherence to semantic versioning standards
> > * Configuration components should be enhanced to compare and return the configuration item with the latest version, when no filter is specified
> > * To support backward compatibility, if version items does not follow standards of semantic versioning, system should compare major and minor versions and return the item with highest version.
> 
> Versioning would help with differentiating the configuration changes and App may have more control now, however
> 
> 1. Does the App need to keep track of the versioning?
The App is free to choose the version it wants to leverage, by specifying the version ID in the GET request as metadata. If the App is not aware of the version, querying for the key should return the latest version. That is the behaviour we are trying to implement with this proposal.


> 2. How do you handle the existing implementations?
Existing configuration functionality will continue to work as-is if the configuration items are not compliant to semantic versioning.

**Comment by akhilac1** [comment] 2022-10-20 13:52
@berndverst - Can you please add this to 1.10
Justification - This proposal makes the response to GET ALL Keys more reliable by disambiguating the configuration that would be returned when no keys are specified.

**Comment by akhilac1** [comment] 2022-10-20 13:53
@pravinpushkar @rabollin - FYI Please

**Comment by rabollin** [comment] 2022-11-24 15:57
Commenting to keep the issue active

**Comment by rabollin** [comment] 2022-12-24 19:11
This is being addressed as part of https://github.com/dapr/dapr/issues/5522 for 1.10

**Comment by shivamkm07** [comment] 2023-04-12 13:31
@ItalyPaleAle @berndverst Can you please review the above proposal and confirm if this is the expected behaviour we want to go with:

Current Behaviour: User can use any value as version in the configStore and it would be supported as far as it's string. If there are multiple Versions of a given key, any random of these are returned. However, if a specific version is passed as metadata, only that would be returned. 

Proposed Behaviour: We only allow version to be a correct semantic version, and if it's not, we ignore that value. Note that we don't have write permissions to config store, and so a user can always store a key with non-semantic version. But when we do `get` for the key from the config store, in that case we just ignore the value if it's version is non-semantic. in case of multiple semantic versions, we return the latest semantic version. 

Note that proposed behaviour would be a breaking change for someone who would be using the config API (although it's in alpha for now and so if we have to do the change, it has to be done now, before moving to stable).

**Comment by ItalyPaleAle** [comment] 2023-04-12 13:55
@shivamkm07 

- what’s the reason why there have to be multiple versions in the configuration? Can’t we just have a single “latest” version?
- If multiple versions are absolutely required, I’m ok with looking at the highest version, but I think using semver would unnecessarily complicate this. Just say that version must be an integer (perhaps stored as a string) and we’ll pick the highest one. This way users can use simple counters (0, 1, 2…) or the ISO timestamp (20230412065533)

**Comment by shivamkm07** [comment] 2023-04-12 16:01
> what’s the reason why there have to be multiple versions in the configuration? Can’t we just have a single “latest” version?

There are config stores like postgres which support storing multiple versions, and it is done `outside` of dapr i.e. we don't write in config stores. So in those scenarios, when users have stored multiple versions of a key in the store, we need to handle that in the `get` operation. In other words, it's not us who control whether there are single/multiple versions in the store, since we don't have write permissions.

> If multiple versions are absolutely required, I’m ok with looking at the highest version, but I think using semver would unnecessarily complicate this. Just say that version must be an integer (perhaps stored as a string) and we’ll pick the highest one. This way users can use simple counters (0, 1, 2…) or the ISO timestamp (20230412065533)

Strictly limiting to only numbers/counters would cause issues to users who are actually using semver versions like 1.1.0, 2.3.0 etc. Since that's a more standard form of versioning would it be okay to not support semver versions?

**Comment by ItalyPaleAle** [comment] 2023-04-12 16:08
> Strictly limiting to only numbers/counters would cause issues to users who are actually using semver versions like 1.1.0, 2.3.0 etc. Since that's a more standard form of versioning would it be okay to not support semver versions?

Is support for semver something that's been asked?

**Comment by shivamkm07** [comment] 2023-04-12 16:14
> > Strictly limiting to only numbers/counters would cause issues to users who are actually using semver versions like 1.1.0, 2.3.0 etc. Since that's a more standard form of versioning would it be okay to not support semver versions?
> 
> Is support for semver something that's been asked?

Not that I know of. It's just that it needs to be decided what should be the allowed values for `version` field and in case multiple versions are there, what should be returned in `get` call. As we won't be able to change after we move to stable, since it would be considered a breaking change then. 

I am though okay with supporting numbers/counters as well.

**Comment by berndverst** [comment] 2023-04-12 19:28
> > > Strictly limiting to only numbers/counters would cause issues to users who are actually using semver versions like 1.1.0, 2.3.0 etc. Since that's a more standard form of versioning would it be okay to not support semver versions?
> > 
> > 
> > Is support for semver something that's been asked?
> 
> Not that I know of. It's just that it needs to be decided what should be the allowed values for `version` field and in case multiple versions are there, what should be returned in `get` call. As we won't be able to change after we move to stable, since it would be considered a breaking change then.
> 
> I am though okay with supporting numbers/counters as well.

@shivamkm07 Maybe you can introduce a metadata property for the versioning scheme? Alphabetic, numeric, semver etc -- this property should be supported by every configuration store.

Without this property: if multiple versions exist and the service does not indicate which version actually is the latest version then we should throw an error indicating that multiple versions exist and a version is required.

**Comment by ItalyPaleAle** [comment] 2023-04-12 20:01
I'm ok offering semver as an option, but I agree this shouldn't be the default. Semver makes sense when we want to differentiate between minor and major changes, and I am not sure this is needed here. It's more complex for people to manage and more costly for us to handle in a hot path.

**Comment by shivamkm07** [comment] 2023-04-18 06:47
It has been added in Postgres config store in #2740 and not required in redis since redis doesn't support storing multiple versions of key.
For other components it can be added while implementing their certification test. 
Can we close this issue then? @ItalyPaleAle @berndverst

**Closed** 2023-04-18 06:50 UTC
