### ISSUE TITLE
pubsub.mqtt: all messages are sent to the same handler regardless of topic

### ISSUE THREAD

**Issue by ItalyPaleAle** [dapr/components-contrib#1735] opened 2022-05-20 17:12 UTC
I have pinpointed this issue in the code and will include a fix in a PR soon.

## Repro code

Component:

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: orders
spec:
  type: pubsub.mqtt
  version: v1
  metadata:
    - name: url
      value: "tcp://127.0.0.1:1883"
    - name: qos
      value: 1
```

Code:

```go
package main

import (
	"context"
	"errors"
	"log"
	"math/rand"
	"net/http"

	"github.com/dapr/go-sdk/service/common"
	daprd "github.com/dapr/go-sdk/service/http"
)

var sub1 = &common.Subscription{
	PubsubName: "orders",
	Topic:      "topic1",
	Route:      "/checkout1",
}
var sub2 = &common.Subscription{
	PubsubName: "orders",
	Topic:      "topic2",
	Route:      "/checkout2",
}

func main() {
	s := daprd.NewService("127.0.0.1:6002")
	if err := s.AddTopicEventHandler(sub1, eventHandler1); err != nil {
		log.Fatalf("error adding topic 1 subscription: %v", err)
	}
	if err := s.AddTopicEventHandler(sub2, eventHandler2); err != nil {
		log.Fatalf("error adding topic 2 subscription: %v", err)
	}
	if err := s.Start(); err != nil && err != http.ErrServerClosed {
		log.Fatalf("error listenning: %v", err)
	}
}

func eventHandler1(ctx context.Context, e *common.TopicEvent) (retry bool, err error) {
	log.Printf("eventHandler1 (topic=%s): Subscriber received: %s", e.Topic, e.Data)
	log.Printf("eventHandler1 (topic=%s): Done processing: %s", e.Topic, e.Data)
	return false, nil
}

func eventHandler2(ctx context.Context, e *common.TopicEvent) (retry bool, err error) {
	log.Printf("eventHandler2 (topic=%s): Subscriber received: %s", e.Topic, e.Data)
	log.Printf("eventHandler2 (topic=%s): Done processing: %s", e.Topic, e.Data)
	return false, nil
}

```

Run:

```sh
dapr run \
    --app-id myapp \
    --app-port 6002 \
    --dapr-http-port 3602 \
    --dapr-grpc-port 60002 \
    --components-path ./components \
    --log-level debug \
    --\
        go run main.go
```

Send messages to the two topics:

```sh
curl \
    -X POST \
    "http://localhost:3602/v1.0/publish/orders/topic1" \
    -H "Content-Type: application/json" \
    -d "{\"orderId\": \"1"}"
curl \
    -X POST \
    "http://localhost:3602/v1.0/publish/orders/topic2" \
    -H "Content-Type: application/json" \
    -d "{\"orderId\": \"2"}"
```

## Expected Behavior

Should log:

```
eventHandler1 (topic=topic1): Subscriber received: map[orderId:1]
eventHandler1 (topic=topic1): Done processing: map[orderId:1]
eventHandler2 (topic=topic2): Subscriber received: map[orderId:2]
eventHandler2 (topic=topic2): Done processing: map[orderId:2]
```

## Actual Behavior

Logs:

```
eventHandler2 (topic=topic1): Subscriber received: map[orderId:1]
eventHandler2 (topic=topic1): Done processing: map[orderId:1]
eventHandler2 (topic=topic2): Subscriber received: map[orderId:2]
eventHandler2 (topic=topic2): Done processing: map[orderId:2]
```

(Sometimes all messages go to `eventHandler1` instead, depending on which one is registered first)

## Release Note

RELEASE NOTE: **FIX** Routing pubsub.mqtt messages to the correct handler when more than one is registered

**Comment by yaron2** [comment] 2022-05-20 19:31
Dupe of https://github.com/dapr/components-contrib/issues/1709. Closing

**Closed by yaron2** 2022-05-20 19:31 UTC
Labels: kind/bug
