### ISSUE TITLE
Azure Service Bus Component - Add "decode base64 message" option to input bindings

### ISSUE THREAD

**Issue by subesokun** [dapr/components-contrib#232] opened 2020-02-24 12:30 UTC
## Describe the proposal

When connecting an Azure service bus queue or Azure storage queue (maybe also event hub) to a storage account to receive e.g. the blob created events, all queue messages/events are base64 encoded. This will cause an error in the application in case the POST route handler applies an automated JSON parsing of the body (because the headers have the content-type `application/json`) so a special middleware has to be added to decode the message before it gets parsed.

Instead, it'd be great if there is an option like "decode base64 message" so that the application doesn't need to implement the decoding logic.

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: <name>
spec:
  type: bindings.azure.servicebusqueues
  metadata:
  - name: connectionString
    value: https://***
  - name: queueName
    value: queue1
  - name: decodeMessage
    value: true
```

**Comment by artursouza** [comment] 2020-02-24 21:48
@youngbupark @yaron2 We can start by implementing this in the specific component mentioned here. If this proves to be a common need for other components, then it might be worth to bake it into the runtime.

**Comment by yaron2** [comment] 2020-02-24 21:51
I agree.

**Comment by CarlosLanderas** [comment] 2020-03-04 21:45
Hello @subesokun!
As I work quite a lot with Azure storage and Service bus I wanted to recreate your environment to contribute with a PR and add the decodeMessage feature.

Could you add some information about the steps you are following? I created and Azure event grid subscription from Azure storage with blob events redirected to Azure service bus queues and it is not base64 encoded.

Are you using az functions?

**Comment by CarlosLanderas** [comment] 2020-03-05 10:53
I have this change working in a local branch, however there is something I would like to ask. The dapr api method onOutputBindingMessage, is marshalling the data request payload to []uint8 and it is including the string quotes in the target data message:

https://github.com/dapr/dapr/blob/master/pkg/http/api.go#L254

When you try to decode the base64 it is invalid so you need to trim the string payload:

```go
if a.metadata.DecodeBase64 == "true" {
			if decoded, err := decodeBase64Data(msg.Data); err == nil {
				msg.Data = decoded
```

```go
func decodeBase64Data(data []byte) ([]byte, error) {
	data = bytes.Trim(data, "\"") //Need to trim the byte array
	decoded := make([]byte, base64.StdEncoding.DecodedLen(len(data)))
	_, err := base64.StdEncoding.Decode(decoded, data)

	if err != nil {
		return nil, err
	}

	return decoded, nil
}
```
If you do not try to decode the message the target application is receiving the message with quotes but we need to do this trimming to decode the base64 as far as I know. (More a C# guy :P)

Is this something we want to do?

**Comment by subesokun** [comment] 2020-03-05 13:16
@CarlosLanderas Just let me double-checked that I'm not mixing up things here. I thought that I've also observed this behavior with the Service Bus and not only with the Storage Queue. But I'll try to reproduce it with the Service Bus.

My last setup looked like the following:

Azure Blob Storage -> Event -> Storage Queue -> Local running Dapr app (Node.JS based). For the HTTP server, I was using Fastify instead of Express. And I was using the Azure Portal for uploading the blob file.

**Comment by CarlosLanderas** [comment] 2020-03-05 13:41
Hello @subesokun, thanks for your answer :)
I am using the events section in storage account. If I create an event grid subscriptions from Blob Storage to Azure Service Bus and a input binding I obtain the following payload in a golang dapr app:

```json
{
   "topic":"/subscriptions/2a9be777-4217-4473-87cc-f539de44d0f3/resourceGroups/lande-we/providers/Microsoft.Storage/storageAccounts/teststorage123lande",
   "subject":"/blobServices/default/containers/container1/blobs/AD",
   "eventType":"Microsoft.Storage.BlobCreated",
   "eventTime":"2020-03-05T09:00:37.1101536Z",
   "id":"f1830947-c01e-00ce-47cc-f29df506f80f",
   "data":{
      "api":"PutBlockList",
      "clientRequestId":"d7286a2b-1b8c-417c-9228-740d6bdf302c",
      "requestId":"f1830947-c01e-00ce-47cc-f29df5000000",
      "eTag":"0x8D7C0E3ABF21047",
      "contentType":"application/octet-stream",
      "contentLength":518,
      "blobType":"BlockBlob",
      "url":"https://teststorage123lande.blob.core.windows.net/container1/AD",
      "sequencer":"000000000000000000000000000026FD0000000001603668",
      "storageDiagnostics":{
         "batchId":"60f44233-0006-0035-00cc-f2206f000000"
      }
   },
   "dataVersion":"",
   "metadataVersion":"1"
}
```

**Comment by CarlosLanderas** [comment] 2020-03-05 13:55
Ok, I think the problem is with Azure Storage Queues:

Binding input:

eyJ0b3BpYyI6Ii9zdWJzY3JpcHRpb25zLzJhOWJlNzc3LTQyMTctNDQ3My04N2NjLWY1MzlkZTQ0ZDBmMy9yZXNvdXJjZUdyb3Vwcy9sYW5kZS13ZS9wcm92aWRlcnMvTWljcm9zb2Z0LlN0b3JhZ2Uvc3RvcmFnZUFjY291bnRzL3Rlc3RzdG9yYWdlMTIzbGFuZGUiLCJzdWJqZWN0IjoiL2Jsb2JTZXJ2aWNlcy9kZWZhdWx0L2NvbnRhaW5lcnMvY29udGFpbmVyMS9ibG9icy9BRCIsImV2ZW50VHlwZSI6Ik1pY3Jvc29mdC5TdG9yYWdlLkJsb2JEZWxldGVkIiwiZXZlbnRUaW1lIjoiMjAyMC0wMy0wNVQxMzo1NDoyMC4wODg4ODQ4WiIsImlkIjoiOWEzZTY3NWUtNzAxZS0wMTIwLTQyZjUtZjJjOWQxMDYyYWQ3IiwiZGF0YSI6eyJhcGkiOiJEZWxldGVCbG9iIiwicmVxdWVzdElkIjoiOWEzZTY3NWUtNzAxZS0wMTIwLTQyZjUtZjJjOWQxMDAwMDAwIiwiZVRhZyI6IjB4OEQ3QzEwQ0I0MEY1RTEwIiwiY29udGVudFR5cGUiOiJhcHBsaWNhdGlvbi9vY3RldC1zdHJlYW0iLCJjb250ZW50TGVuZ3RoIjo1MTgsImJsb2JUeXBlIjoiQmxvY2tCbG9iIiwidXJsIjoiaHR0cHM6Ly90ZXN0c3RvcmFnZTEyM2xhbmRlLmJsb2IuY29yZS53aW5kb3dzLm5ldC9jb250YWluZXIxL0FEIiwic2VxdWVuY2VyIjoiMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDI2RkQwMDAwMDAwMDAxYTg0NmMwIiwic3RvcmFnZURpYWdub3N0aWNzIjp7ImJhdGNoSWQiOiI2MTgzMGNjMC0wMDA2LTAwMzUtMDBmNS1mMjIwNmYwMDAwMDAifX0sImRhdGFWZXJzaW9uIjoiIiwibWV0YWRhdGFWZXJzaW9uIjoiMSJ9

Decoded:

{"topic":"/subscriptions/2a9be777-4217-4473-87cc-f539de44d0f3/resourceGroups/lande-we/providers/Microsoft.Storage/storageAccounts/teststorage123lande","subject":"/blobServices/default/containers/container1/blobs/AD","eventType":"Microsoft.Storage.BlobDeleted","eventTime":"2020-03-05T13:54:20.0888848Z","id":"9a3e675e-701e-0120-42f5-f2c9d1062ad7","data":{"api":"DeleteBlob","requestId":"9a3e675e-701e-0120-42f5-f2c9d1000000","eTag":"0x8D7C10CB40F5E10","contentType":"application/octet-stream","contentLength":518,"blobType":"BlockBlob","url":"https://teststorage123lande.blob.core.windows.net/container1/AD","sequencer":"000000000000000000000000000026FD0000000001a846c0","storageDiagnostics":{"batchId":"61830cc0-0006-0035-00f5-f2206f000000"}},"dataVersion":"","metadataVersion":"1"}

**Comment by artursouza** [comment] 2020-04-07 23:07
Can we close this issue?

**Comment by CarlosLanderas** [comment] 2020-04-07 23:47
Yes sorry! It's merged. Closing

**Closed** 2020-04-07 23:49 UTC
Labels: P1, area/bindings, kind/enhancement

**Comment by subesokun** [comment] 2020-04-08 12:21
Sorry for the late feedback and thank you for the fix :) !
