### ISSUE TITLE
PubSub Azure Service Bus periodically stops working due to authentication issues

### ISSUE THREAD

**Issue by bgelens** [dapr/components-contrib#1148] opened 2021-09-15 10:45 UTC
## Expected Behavior

Continue to operate normally

## Actual Behavior

Periodically our pubsub with Azure Service Bus stops working due to authentication issues. We have this issue on multiple clusters where (it looks like) our Acceptance cluster basically has it on the same day as our Production cluster (probably because we accept Acceptance and roll through Production on the same day)

AFAICT, it happened on

* August 3th
* August 25th
* September 15th

It seems to be a pattern that repeats every 20-some days.

The symptoms are that we aren't receiving any more messages. The cause is seen in the dapr sidecar logging. Basically an authentication issue as it seems.

`2021-09-15T05:52:09.809Z time="2021-09-15T05:52:09.809304727Z" level=error msg="azure service bus error: error receiving message on topic REDACTED, link detached, reason: *Error{Condition: amqp:link:detach-forced, Description: The link 'SfpRLmiAbJgr9e1tqh8pHkZ7xDDkRJaTc4bplkN9nlk2DPnoV_iHbQ' is force detached. Code: RenewToken. Details: Unauthorized access. 'Listen' claim(s) are required to perform this operation. Resource: 'REDACTED'.. TrackingId:62d462fb5fd548e29418a58cdebbb11d_G24, SystemTracker:gateway7, Timestamp:2021-09-15T05:52:09, Info: map[]}" app_id= REDACTED instance= REDACTED scope=dapr.contrib type=log ver=1.2.2 2021-09-15T05:52:09.809Z time="2021-09-15T05:52:09.809333928Z" level=warning msg="Subscription to topic REDACTED lost connection, attempting to reconnect... [0/30]" app_id= REDACTED instance= REDACTED scope=dapr.contrib type=log ver=1.2.2 2021-09-15T06:57:03.912Z time="2021-09-15T06:57:03.911865689Z" level=warning msg="azure service bus error: closing subscription entity for topic REDACTED: link detached, reason: *Error{Condition: amqp:link:detach-forced, Description: The link 'QLcCY6xfo57kXvlhZB0XJv4nz7jPLoNyJKy2PP6KO7N4gGlLdM9aEg' is force detached. Code: RenewToken. Details: Unauthorized access. 'Listen' claim(s) are required to perform this operation. Resource: 'REDACTED'.. TrackingId:120749e74bd6464a8f7efb733b0758c6_G2, SystemTracker:gateway7, Timestamp:2021-09-15T06:57:03, Info: map[]}" app_id= REDACTED instance=REDACTED scope=dapr.contrib type=log ver=1.2.2`

## Steps to Reproduce the Problem

Wait for it to happen every 20-ish days

## Additional Info

dapr 1.2.2 deploy in AKS (1.20.9) in HA mode using Helm chart reporting healthy

Servicebus Standard tier with global shared access policy for dapr with manage send and listen permission

pub sub component:

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  annotations:
    meta.helm.sh/release-name: REDACTED
    meta.helm.sh/release-namespace: REDACTED
  creationTimestamp: "2021-06-18T13:18:11Z"
  generation: 1
  labels:
    app.kubernetes.io/managed-by: Helm
  name: dapr-pubsub-component
  namespace: REDACTED
  resourceVersion: "81954849"
  uid: 4f232902-bb98-470e-9167-2a64ec19c2df
spec:
  metadata:
  - name: connectionString
    value: Endpoint=sb://REDACTED.servicebus.windows.net/;SharedAccessKeyName= REDACTED;SharedAccessKey= REDACTED
  - name: timeoutInSec
    value: "60"
  - name: handlerTimeoutInSec
    value: "60"
  - name: disableEntityManagement
    value: "false"
  - name: maxDeliveryCount
    value: ""
  - name: lockDurationInSec
    value: ""
  - name: lockRenewalInSec
    value: ""
  - name: maxActiveMessages
    value: ""
  - name: maxActiveMessagesRecoveryInSec
    value: ""
  - name: maxConcurrentHandlers
    value: ""
  - name: prefetchCount
    value: ""
  - name: defaultMessageTimeToLiveInSec
    value: ""
  - name: autoDeleteOnIdleInSec
    value: ""
  type: pubsub.azure.servicebus
  version: v1
```

Originally mentioned in: #874

**Comment by bgelens** [comment] 2021-09-15 10:45
@jjcollinge if there is anything more you need, please let me know

**Comment by jjcollinge** [comment] 2021-09-15 11:16
This looks good, thanks for raising it. Due to the nature of the issue it may take a while to root cause this but I'll work with the SDK team to see if we can repro. One thing to mention is that we bumped the version of the SDK Dapr is using here in [this PR](https://github.com/dapr/components-contrib/pull/1132) which I believe will be released in Dapr v1.5. This does include a bunch of changes to how the links work under the hood so may resolve this - if you could test that out and report back that'd be great - thanks.

**Comment by bgelens** [comment] 2021-09-15 12:26
We are about to upgrade our clusters to 1.3 end of month. I could run an early build in Dev but not sure how I can test with 1.5 at this time as 1.4RC7 is the latest available.  Any pointers? Or should I wait for a pre-release post 1.4 GA?

**Comment by jjcollinge** [comment] 2021-09-15 16:27
There won't be any release candidates for 1.5 for a while - if you want to test sooner you'll need to build from source and include [this](https://github.com/dapr/components-contrib/commit/45f577e137a6188be88606c1f9c9be34ff6adc04) change. You can follow [these](https://github.com/dapr/components-contrib/blob/master/docs/developing-component.md) instructions to clone both `dapr` and `components-contrib` - in the `dapr` repo run `go mod edit -replace github.com/dapr/components-contrib=../components-contrib` and then follow [these](https://github.com/dapr/dapr/blob/master/docs/development/developing-dapr.md#developing-on-kubernetes-environment) instructions to build, push and deploy your custom Dapr image to your dev cluster. HTH.

**Comment by bgelens** [comment] 2021-09-17 07:53
@jjcollinge We are moving to 1.4 in production instead of 1.3.

I'm not allowed to run a custom build on our clusters. If time permits, I'll try to setup a repro environment (no promises)

**Comment by bgelens** [comment] 2021-11-11 12:17
@jjcollinge Do you want to keep this issue open so I can report back on 1.5 experience?

**Comment by bgelens** [comment] 2021-11-12 11:54
@jjcollinge I've upgraded 2 of our clusters to 1.5. Our production for now remains on 1.4.2 for now which allows to compare.

We did start to notice issues occur on the publishing side as well, this is where we loose data with 1.4 as they are not retried and currently we did not expect the need to handle this.

```
Publish operation failed: the Dapr endpoint indicated a failure. See InnerException for details. Status(StatusCode="Internal", Detail="error when publish to topic mytopic in mycomponent: read tcp podprivateip:52148->servicebuspublicip:5671: read: connection reset by peer") 
```

Do you know if work in the 1.5 release maybe addresses this? We are thinking about adding our own retry logic by catching the daprexception but afaia this would be something dapr should do for us (right?)

**Comment by artursouza** [comment] 2021-11-12 22:13
@bgelens we plan to start work on resiliency for all building blocks in 1.6. At this point, I would recommend to have retry logic to publish on the app.

This is the issue to tackle this: https://github.com/dapr/dapr/issues/3586

**Comment by kalpchipsoft** [comment] 2021-11-27 13:27
Updated to dapr 1.5. But still getting this error.  Any other configuration that I can recheck? Getting this error frequently!
`{"app_id":"operationprocessservice","instance":"operationprocessservice-55f668865b-bpsv7","level":"error","msg":"azure service bus error: error receiving message on topic Operation, link detached, reason: *Error{Condition: amqp:link:detach-forced, Description: The link 'KhtSdCeTmDPYrJ63USaxZ_l0RhmYW1TploN6aDis' is force detached. Code: RenewToken. Details: Unauthorized access. 'Listen' claim(s) are required to perform this operation.`

**Comment by bgelens** [comment] 2021-11-29 09:52
@jjcollinge we have been running 1.5 for about 2 weeks now (in production). So far it looks way more stable. We still have the detached / renewtoken errors in the sidecar logs but we have learned to not be triggered by them, they seem to recover just fine, every retry is a single one. It might be good to reduce the noise in the logging about these events and only log when x amount of reconnects are failing?

Also the publishing errors seem to not occur anymore!

**Comment by jjcollinge** [comment] 2021-12-30 16:00
@bgelens glad to hear v1.5 is more stable so far. Please keep us up to date should things change. There's also some background working going on for a V2 service bus component that hopefully will improve stability even more. @kalpchipsoft do you see any bad behaviour other than this error being logged - or does Dapr recover ok? You may be safe to ignore this error for the time being if it behaves ok.

**Comment by kalpchipsoft** [comment] 2022-01-03 07:34
@jjcollinge No bad behaviour.

**Comment by yaron2** [comment] 2022-01-03 17:20
That's great to hear, thanks for the feedback @bgelens and @kalpchipsoft. Closing this issue for now.

**Closed by yaron2** 2022-01-03 17:20 UTC
Labels: kind/bug

**Comment by bgelens** [comment] 2022-01-05 14:41
@jjcollinge @yaron2 Had a new incident today where messages where not received anymore and we had to restart the pod again. From the logs there were a couple of noticeable errors that stood out. It seems the component was not able to recover from this.

```json
{
  "app_id": "myapp",
  "instance": "myapp-766cf76ccc-hc4nb",
  "level": "error",
  "msg": "azure service bus error: error receiving message on topic mytopic, *Error{Condition: amqp:internal-error, Description: The service was unable to process the request; please retry the operation. For more information on exception types and proper exception handling, please refer to http://go.microsoft.com/fwlink/?LinkId=761101 TrackingId:a3acaac592d64190aa7db6e3f6f5d474_G17, SystemTracker:gateway7, Timestamp:2022-01-05T06:37:17, Info: map[]}",
  "scope": "dapr.contrib",
  "time": "2022-01-05T06:37:17.939418788Z",
  "type": "log",
  "ver": "1.5.1"
}
```

```json
{
  "app_id": "myapp",
  "instance": "myapp-766cf76ccc-hc4nb",
  "level": "error",
  "msg":
    "azure service bus error: error receiving message on topic mytopic, *Error{Condition: amqp:internal-error, Description: The service was unable to process the request; please retry the operation. For more information on exception types and proper exception handling, please refer to htt
    p://go.microsoft.com/fwlink/?LinkId=761101 TrackingId:ddcd04ef75eb4c31b9832593f3fd0a5a_G8, SystemTracker:gateway7, Timestamp:2022-01-0
    5T06:37:22, Info: map[]}",
  "scope": "dapr.contrib",
  "time": "2022-01-05T06:37:23.098448572Z",
  "type": "log",
  "ver": "1.5.1",
}
```

The only way to get messages processed again was to restart the deployment (therefore creating new pods / sidecars)

For the rest there where the normal errors with regard to link detaching and token renewtoken.

Can we reopen this issue or should we transfer to a new one?

**Comment by bgelens** [comment] 2022-01-05 15:53
Hey @jjcollinge, thanks for the quick response.

These are the consecutive logs from the same topic subscription. It looks like it's trying to recover but as the messages where building up in the topic subscription, they where not received anymore

```json
{
  "app_id": "myapp",
  "instance": "myapp-766cf76ccc-hc4nb",
  "level": "error",
  "msg":"azure service bus error: error receiving message on topic mytopic, *Error{Condition: amqp:internal-error, Description: The service was unable to process the request; please retry the operation. For more information on exception types and proper exception handling, please refer to htt
  p: //go.microsoft.com/fwlink/?LinkId=761101 TrackingId:ddcd04ef75eb4c31b9832593f3fd0a5a_G8, SystemTracker:gateway7, Timestamp:2022-01-0
  5T06: 37: 22, Info: map[]
}","scope":"dapr.contrib","time":"2022-01-05T06: 37: 23.098448572Z","type":"log","ver":"1.5.1"}
  {
  "app_id": "myapp",
  "instance": "myapp-766cf76ccc-hc4nb",
  "level": "warning",
  "msg": "Subscription to topic mytopic lost connection, attempting to reconnect... [1/30]",
  "scope": "dapr.contrib",
  "time": "2022-01-05T06:37:23.098541072Z",
  "type": "log",
  "ver": "1.5.1"
}
  {
  "app_id": "myapp",
  "instance": "myapp-766cf76ccc-hc4nb",
  "level": "error",
  "msg": "azure service bus error: error receiving message on topic mytopic, link detached, reason: *Error(nil)",
  "scope": "dapr.contrib",
  "time": "2022-01-05T06:38:12.870542557Z",
  "type": "log",
  "ver": "1.5.1"
}
  {
  "app_id": "myapp",
  "instance": "myapp-766cf76ccc-hc4nb",
  "level": "warning",
  "msg": "Subscription to topic mytopic lost connection, attempting to reconnect... [1/30]",
  "scope": "dapr.contrib",
  "time": "2022-01-05T06:38:12.870605057Z",
  "type": "log",
  "ver": "1.5.1"
}
{
  "app_id": "myapp",
  "instance": "myapp-766cf76ccc-hc4nb",
  "level": "warning",
  "msg": "azure service bus error: closing subscription entity for topic mytopic: read tcp 10.12.4.218:39746-\u003e51.144.124.255:5671: read: connection reset by peer",
  "scope": "dapr.contrib",
  "time": "2022-01-05T06:57:58.652352619Z",
  "type": "log",
  "ver": "1.5.1"
}
{
  "app_id": "myapp",
  "instance": "myapp-766cf76ccc-hc4nb",
  "level": "error",
  "msg": "azure service bus error: error receiving message on topic mytopic, read tcp 10.12.4.218:39746-\u003e51.144.124.255:5671: read: connection reset by peer",
  "scope": "dapr.contrib",
  "time": "2022-01-05T06:57:58.652415919Z",
  "type": "log",
  "ver": "1.5.1"
}
{
  "app_id": "myapp",
  "instance": "myapp-766cf76ccc-hc4nb",
  "level": "warning",
  "msg": "Subscription to topic mytopic lost connection, attempting to reconnect... [0/30]",
  "scope": "dapr.contrib",
  "time": "2022-01-05T06:57:58.652439919Z",
  "type": "log",
  "ver": "1.5.1"
}
```

It'll be hard to reproduce as we where pretty much stable for the past 6 weeks or so.

Let me know if you need anything else

**Comment by b26** [comment] 2022-01-14 20:35
I have similar issues but they are not authentication based and its on GCP not Azure. I don't see any sort of authentication errors in the logs.

![image](https://user-images.githubusercontent.com/2287343/149581201-1e5502af-f4d1-41cf-a1da-cc39b8397586.png)

sometimes undelivered messages can explode. the only solution is to restart the pod.

**Comment by rogerex** [comment] 2022-04-08 01:14
I got the same issue but it only happens when 1.7 RC.1 has no HA enabled
`time="2022-04-07T23:57:03.828812055Z" level=warning msg="azure service bus error: closing subscription entity for topic dapr_xyz: link detached, reason: *Error{Condition: amqp:link:detach-forced, Description: The link 'oCp6GmgdlT2fQ987trzcFHJMXNDaK8TlqKUru4bpYTOoj7g--xgS_A' is force detached. Code: RenewToken. Details: Unauthorized access. 'Listen' claim(s) are required to perform this operation. Resource: 'sb://bla-bla-bla.servicebus.windows.net/dapr_xyz/subscriptions/yuhu'.. TrackingId:0e7ce83b2b9548609fb141cd50048c04_G5, SystemTracker:gateway7, Timestamp:2022-04-07T23:57:03, Info: map[]}" app_id=abc instance=abc-deployment-9bc894c66-chksp scope=dapr.contrib type=log ver=1.7.0-rc.1`

**Comment by ivanmagdic** [comment] 2022-04-12 07:29
Hey @rogerex, we are facing the same issue, and want to resolve it. When you mention "has no HA enabled", you mean that DAPR is not deployed in highly available mode (https://docs.dapr.io/operations/hosting/kubernetes/kubernetes-production#highly-available-mode)?

To clarify, deploying DAPR in HA **might** resolve this?
