### ISSUE TITLE
Kafka Multi subscribe Error

### ISSUE THREAD

**Issue by springe2004** [dapr/components-contrib#3249] opened 2023-11-24 03:45 UTC
Using dapr to subscribe to multiple topics：

level=error msg="Error consuming [topicname]. Retrying...: kafka: tried to use a consumer group that was closed" app_id=sub component="pubsub (pubsub.kafka/v1)"

note:There is no problem with two subscriptions, exceeding two will result in an error

## Release Note
dapr 1.12.2
kafka ->redpanda

**Comment by olitomlinson** [comment] 2023-12-04 22:02
Other reports of the same issue : https://github.com/dapr/dapr/issues/7235

**Comment by yaron2** [comment] 2023-12-21 18:53
Closing as duplicate of #3263

**Closed by yaron2** 2023-12-21 18:53 UTC
Labels: kind/bug
