### ISSUE TITLE
Fail to build `dapr/dapr` with latest `dapr/components-contrib`

### ISSUE THREAD

**Issue by Jarema** [dapr/components-contrib#2189] opened 2022-10-13 12:52 UTC
## Expected Behavior

Have working dev env following https://github.com/dapr/components-contrib/blob/master/docs/developing-component.md

## Actual Behavior

Replacing `components-contrib` dependency in `dapr/dapr` results in abigous imports error:

```
✦ ❯ make modtidy
go mod tidy
github.com/dapr/dapr/cmd/daprd/components imports
        github.com/dapr/components-contrib/pubsub/pulsar imports
        github.com/apache/pulsar-client-go/pulsar imports
        github.com/apache/pulsar-client-go/pulsar/internal/auth imports
        github.com/apache/pulsar-client-go/oauth2: ambiguous import: found package github.com/apache/pulsar-client-go/oauth2 in multiple modules:
        github.com/apache/pulsar-client-go v0.9.0 (/Users/tomaszpietrek/go/pkg/mod/github.com/apache/pulsar-client-go@v0.9.0/oauth2)
        github.com/apache/pulsar-client-go/oauth2 v0.0.0-20220120090717-25e59572242e (/Users/tomaszpietrek/go/pkg/mod/github.com/apache/pulsar-client-go/oauth2@v0.0.0-20220120090717-25e59572242e)
github.com/dapr/dapr/cmd/daprd/components imports
        github.com/dapr/components-contrib/pubsub/pulsar imports
        github.com/apache/pulsar-client-go/pulsar imports
        github.com/apache/pulsar-client-go/pulsar/internal/auth imports
        github.com/apache/pulsar-client-go/oauth2/cache: ambiguous import: found package github.com/apache/pulsar-client-go/oauth2/cache in multiple modules:
        github.com/apache/pulsar-client-go v0.9.0 (/Users/tomaszpietrek/go/pkg/mod/github.com/apache/pulsar-client-go@v0.9.0/oauth2/cache)
        github.com/apache/pulsar-client-go/oauth2 v0.0.0-20220120090717-25e59572242e (/Users/tomaszpietrek/go/pkg/mod/github.com/apache/pulsar-client-go/oauth2@v0.0.0-20220120090717-25e59572242e/cache)
github.com/dapr/dapr/cmd/daprd/components imports
        github.com/dapr/components-contrib/pubsub/pulsar imports
        github.com/apache/pulsar-client-go/pulsar imports
        github.com/apache/pulsar-client-go/pulsar/internal/auth imports
        github.com/apache/pulsar-client-go/oauth2/clock: ambiguous import: found package github.com/apache/pulsar-client-go/oauth2/clock in multiple modules:
        github.com/apache/pulsar-client-go v0.9.0 (/Users/tomaszpietrek/go/pkg/mod/github.com/apache/pulsar-client-go@v0.9.0/oauth2/clock)
        github.com/apache/pulsar-client-go/oauth2 v0.0.0-20220120090717-25e59572242e (/Users/tomaszpietrek/go/pkg/mod/github.com/apache/pulsar-client-go/oauth2@v0.0.0-20220120090717-25e59572242e/clock)
github.com/dapr/dapr/cmd/daprd/components imports
        github.com/dapr/components-contrib/pubsub/pulsar imports
        github.com/apache/pulsar-client-go/pulsar imports
        github.com/apache/pulsar-client-go/pulsar/internal/auth imports
        github.com/apache/pulsar-client-go/oauth2/store: ambiguous import: found package github.com/apache/pulsar-client-go/oauth2/store in multiple modules:
        github.com/apache/pulsar-client-go v0.9.0 (/Users/tomaszpietrek/go/pkg/mod/github.com/apache/pulsar-client-go@v0.9.0/oauth2/store)
        github.com/apache/pulsar-client-go/oauth2 v0.0.0-20220120090717-25e59572242e (/Users/tomaszpietrek/go/pkg/mod/github.com/apache/pulsar-client-go/oauth2@v0.0.0-20220120090717-25e59572242e/store)
make: *** [modtidy] Error 1

```

Which seem to originate (but I might be wrong) of this change:

![image (1)](https://user-images.githubusercontent.com/7369771/195600916-416f1d04-22c7-4c4e-a9fa-95900c0f8829.png)

(pulsar client version bump)

## Steps to Reproduce the Problem

follow https://github.com/dapr/components-contrib/blob/master/docs/developing-component.md

`make modtidy-all` will fail.

As above

## Release Note

RELEASE NOTE:

**Comment by berndverst** [comment] 2022-10-18 16:06
@Jarema this is not a bug. That will happen from time to time. It's fixed as of yesterday.

**Comment by berndverst** [comment] 2022-10-18 16:09
The latest components-contrib was imported in this PR (and any issues that came up were addressed there): https://github.com/dapr/dapr/pull/5377

**Closed** 2022-10-18 16:10 UTC
Labels: triaged/resolved
