### ISSUE TITLE
Azure configstore component does not pull all keys using connection string

### ISSUE THREAD

**Issue by maXA1m** [dapr/components-contrib#2061] opened 2022-09-09 11:32 UTC
## Expected Behavior

Should work without errors and pull all the keys.

## Actual Behavior

Fails with internal exception:
Status(StatusCode="Internal", Detail="fail to get [] from Configuration store service-configstore: failed to load all keys, error is no Host in request URL")

## Steps to Reproduce the Problem

1. Setup configstore yaml file and set valid connection string to appConfigConnectionString setting.
2. Try to access configuration using AddDaprConfigurationStore extension method from .NET SDK, specify empty List to "keys" parameter.
3. An exception will be thrown.

## Release Note

RELEASE NOTE:

**Comment by cmendible** [comment] 2022-09-10 06:59
Can you try:

``` bash
dapr run -d ../components -H 8080 --enable-api-logging --log-level info
curl -v http://localhost:8080/v1.0-alpha1/configuration/<configuration component name>
```
where `components` contains your `azappconfig` component configuration.

**Comment by maXA1m** [comment] 2022-09-10 07:26
I have Dapr cli 1.8.4 and cannot try azure configstore.
I use docker-compose with edge version and network_mode pointing to my service, what could I try in this case?

**Comment by maXA1m** [comment] 2022-09-10 08:05
`time="2022-09-10T08:02:30.0259446Z" level=info msg="gRPC API Called: /dapr.proto.runtime.v1.Dapr/GetConfigurationAlpha1" app_id=service-api instance=5f577496262e scope=dapr.runtime.grpc.api-info type=log ver=edge
time="2022-09-10T08:02:31.273503Z" level=debug msg="rpc error: code = Internal desc = fail to get [] from Configuration store service-configstore: failed to load all keys, error is no Host in request URL" app_id=service-api instance=5f577496262e scope=dapr.runtime.grpc.api type=log ver=edge`

**Comment by pravinpushkar** [comment] 2022-09-13 09:45
@cmendible I am facing one weird issue while retrieving the values - 
 My configuration store contains these values - 
![Screenshot 2022-09-13 at 3 07 12 PM](https://user-images.githubusercontent.com/33649292/189868812-cb386eed-7933-45cc-88bc-1a167e03d200.png)

But When I try to retrieve, it gives me older values (which have been deleted or updated few hrs back) - 
```
curl -X GET http://localhost:3500/v1.0-alpha1/configuration/pravin-app-config

response - 

{"config1":{"value":"configval1"},"config2":{"value":"configval2"},"myconfig1":{"value":"val1"},"sentinel-config1":{"value":"1"},"sentinel-config2":{"value":"1"}}%
```

**Comment by pravinpushkar** [comment] 2022-09-13 09:54
On further investigation, it seems some issue with `getAll` - 
```
➜  examples git:(feature/config_unsubscribe_api) ✗ curl -X GET http://localhost:3500/v1.0-alpha1/configuration/pravin-app-config\?key\=config1

{"config1":{"value":"configval1_1"}}%

➜  examples git:(feature/config_unsubscribe_api) ✗ curl -X GET http://localhost:3500/v1.0-alpha1/configuration/pravin-app-config\?key\=sentinel-config1

{"sentinel-config1":{"value":"3"}}%

➜  examples git:(feature/config_unsubscribe_api) ✗ curl -X GET http://localhost:3500/v1.0-alpha1/configuration/pravin-app-config

{"config1":{"value":"configval1"},"config2":{"value":"configval2"},"myconfig1":{"value":"val1"},"sentinel-config1":{"value":"1"},"sentinel-config2":{"value":"1"}}%
```

**Comment by cmendible** [comment] 2022-09-13 10:14
> On further investigation, it seems some issue with `getAll` -
> 
> ```
> ➜  examples git:(feature/config_unsubscribe_api) ✗ curl -X GET http://localhost:3500/v1.0-alpha1/configuration/pravin-app-config\?key\=config1
> 
> {"config1":{"value":"configval1_1"}}%
> 
> ➜  examples git:(feature/config_unsubscribe_api) ✗ curl -X GET http://localhost:3500/v1.0-alpha1/configuration/pravin-app-config\?key\=sentinel-config1
> 
> {"sentinel-config1":{"value":"3"}}%
> 
> ➜  examples git:(feature/config_unsubscribe_api) ✗ curl -X GET http://localhost:3500/v1.0-alpha1/configuration/pravin-app-config
> 
> {"config1":{"value":"configval1"},"config2":{"value":"configval2"},"myconfig1":{"value":"val1"},"sentinel-config1":{"value":"1"},"sentinel-config2":{"value":"1"}}%
> ```

Haven't seen that. Probably cause I've not updated values in my tests.

Current filter should retrieve everything according to the SDK documentation:

https://github.com/dapr/components-contrib/blob/9681a71a2a087ac0568affd42efedb39ee3d864b/configuration/azure/appconfig/appconfig.go#L204

**Comment by pravinpushkar** [comment] 2022-09-15 10:38
@maXA1m Show you email late, here is my config yaml - 

```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: xxx
spec:
  type: configuration.azure.appconfig
  version: v1
  metadata:
  - name: appConfigConnectionString
    value: "Endpoint=https://xxx.azconfig.io;Id=<id>;Secret=<secret>"
```

basically you can copy the endpoint directly from azure portal and put here in value section of `appConfigConnectionString`

**Comment by maXA1m** [comment] 2022-09-15 12:17
@pravinpushkar Thanks, looks similar to my config, but I cannot get configuration store component working, I think there is some problem with authentication.

**Comment by pravinpushkar** [comment] 2022-09-16 10:05
@maXA1m I do not see any authentication error. Can you try these steps below - 

```
dapr run --components-path ./components/configuration --app-id confighttp --enable-api-logging --log-level debug --app-port 3009 --dapr-http-port 3500
```
```
curl -X GET http://localhost:3500/v1.0-alpha1/configuration/<xxx>
```

**Comment by pravinpushkar** [comment] 2022-09-16 10:14
> Haven't seen that. Probably cause I've not updated values in my tests.
> 
> Current filter should retrieve everything according to the SDK documentation:
> 
> https://github.com/dapr/components-contrib/blob/9681a71a2a087ac0568affd42efedb39ee3d864b/configuration/azure/appconfig/appconfig.go#L204

The problem is with `delete`and `update` . The deleted keys keep showing in the getAll call. Where as if I add a new key that also comes, which is correct.

See below logs - 
For update - 

➜  examples git:(feature/config_unsubscribe_api) ✗ curl -X GET http://localhost:3500/v1.0-alpha1/configuration/pravin-app-config-2\?key\=config1

**{"config1":{"value":"val111"}}**%
➜  examples git:(feature/config_unsubscribe_api) ✗ curl -X GET http://localhost:3500/v1.0-alpha1/configuration/pravin-app-config-2

**{"config1":{"value":"val1"}**,"config2":{"value":"val2"},"config3":{"value":"val3"},"config4":{"value":"1"},"sentinel-config1":{"value":"1"},"sentinel-config2":{"value":"1"}}%

For deleted keys - 
➜  examples git:(feature/config_unsubscribe_api) ✗ curl -X GET http://localhost:3500/v1.0-alpha1/configuration/pravin-app-config-2

{"config1":{"value":"val1"},"config2":{"value":"val2"},"**config3":{"value":"val3"}**,"sentinel-config1":{"value":"1"},"sentinel-config2":{"value":"1"}}%

➜  examples git:(feature/config_unsubscribe_api) ✗ curl -X GET http://localhost:3500/v1.0-alpha1/configuration/pravin-app-config-2**\?key\=config3**

{"errorCode":"ERR_CONFIGURATION_GET","message":"fail to get [config3] from Configuration store pravin-app-config-2: GET https://pravin-app-config-2.azconfig.io/kv/config3\n--------------------------------------------------------------------------------\nRESPONSE 404: 404 Not Found\

**Comment by pravinpushkar** [comment] 2022-09-19 08:31
Probable reason for getting older keys also with getAll is this - https://github.com/Azure/azure-sdk-for-go/issues/19135
We might need new sdk version to fix this.

**Comment by pravinpushkar** [comment] 2022-09-20 12:23
@cmendible  I have created a new issue and pull request to fix the getAll results. See above.

@maXA1m I could not reproduce the connection string issue that is mentioned originally in this issue. Feel free to close this one if it is not needed anymore.

**Closed** 2022-12-02 21:56 UTC
Labels: kind/bug, P1, pinned
