### ISSUE TITLE
AWS SES components require secretKey and accessKey

### ISSUE THREAD

**Issue by cciobanu98** [dapr/components-contrib#2698] opened 2023-03-23 13:10 UTC
## Expected Behavior

When I create a component like this: 

```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: ses
spec:
  type: bindings.aws.ses
  version: v1
  metadata:
  - name: emailFrom
    value: "myacc@myemail.com"
```

From the documentation if I am using AWS IAM I should not add accessKey and secretKey. 

```
Important
When running the Dapr sidecar (daprd) with your application on EKS (AWS Kubernetes), if you’re using a node/pod that has already been attached to an IAM policy defining access to AWS resources, you must not provide AWS access-key, secret-key, and tokens in the definition of the component spec you’re using.
```

## Actual Behavior

At the moment I am receiving this error
```
[INIT_COMPONENT_FAILURE]: initialization error occurred for ses (bindings.aws.ses/v1): SES binding error: region, accessKey or secretKey fields are required in metadata"
```

## Release Note

RELEASE NOTE:

**Comment by berndverst** [comment] 2023-03-27 21:44
@cciobanu98 can you please go to the linked docs issue dapr/docs#3292 and comment with `/assign` so that the issue is assigned to you?

We may choose to revert any pull requests that do not have documentation.

**Closed** 2023-03-27 22:08 UTC
Labels: kind/bug, documentation required
